# Simple workflow for deploying static content to GitHub Pages with Maintenance Mode
name: Deploy static content to Pages with Maintenance Mode

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  maintenance-on:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Enable Maintenance Mode
        run: |
          echo "<meta http-equiv='refresh' content='0; url=/maintenance.html'>" > index.html
          git add index.html
          git commit -m "Enable maintenance mode"
          git push

  deploy:
    needs: maintenance-on
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  maintenance-off:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Disable Maintenance Mode
        run: |
          git rm index.html
          git commit -m "Disable maintenance mode"
          git push
